### ISSUE TITLE
Script strips newline at end of file

### ISSUE THREAD

**Issue by jdloft** [osterman/copyright-header#27] opened 2015-07-23 18:17 UTC
After I ran the script to add headers to my source, I noticed that all of the files had their newline stripped from the end of the file. This causes many problems related to source control, parsing, and compiling.

**Comment by osterman** [comment] 2015-08-03 09:08
Hrm... that could be the case. Not sure when I will get around to looking at that. Thanks for reporting the issue.

**Comment by thomasrussellmurphy** [comment] 2016-08-20 23:44
I could not reproduce this behavior in the current version of `copyright-header` using a file-based license source.

**Comment by osterman** [comment] 2016-09-08 03:55
Thanks for checking... Will close this for now.

**Closed by osterman** 2016-09-08 03:55 UTC

**Comment by osterman** [comment] 2017-02-24 23:01
Perhaps related: https://github.com/osterman/copyright-header/pull/34
